---
title: "Bug"
category:
    - Javascript
tag:
    - javascript
    - 모던 자바스크립트 인문
toc: true
---

### BUG -버그(원인,strict모드,스타일가이드,개발자도구)/예외처리(throw문,Error객체,try/catch/finally문)

---

### 버그에 대해


* #### 버그의 원인

1. 논리적인 버그

논리적 버그란 프로그램의 바탕이 되는 **알고리즘 자체에 오류**가 있거나 알고리즘을 프로그램으로 구현하는 방법이 잘못되었을 때 발생

(프로그래밍 언어의 문법을 충분히 이해하지 못해 생긴 경우에도 이에 포함됨)


2. 오타

-오타는 오류가 발생하는 않지만 개발자가 의도하지 않은 동작을 유발할 수 있음

-작은 오타도 프로그램에 심각한 오류를 발생시킬 가능성이 있음 


3. 실행환경의 변화

컴퓨터, OS, 프로그래밍 언어 자체의 사양이 바뀌어 프로그램이 동작하지 않는 경우도 있음

(이러한 상황은 버그라고는 할 수 없지만, 프로그램이 동작하지 않는 원인 중 하나일 수 있으므로 기입함)


---

* #### Strict 모드

자바스크립트라는 언어는 다른 언어에 비해 버그가 발생할 확률이 높음

-> ECMAScript 5부터 추가된 Strict모드는 자바스크립트 언어의 사양 중에서 버그를 일으키기 쉬운 부분을 제거함


**HOW?**

1. 버그를 최대한 발생하지 않게 만듦

2. 버그가 발생했을 때 즉시 알 수 있도록 언어의 사양을 엄격하게 제한

3. 일부 기능을 사용할 수 없도록 제한함

4. 자바스크립트 엔진이 내부적으로 최적화 처리에 장애가 되는 부분을 제거함


**Strict모드를 설정하면 바뀌는 점**

1. 변수는 모두 선언해야함. 선언되지 않은 변수, 함수, 함수의 인자에 값을 대입하면 ReferenceError가 발생함

2. 함수를 직접 호출할 때, 함수 안의 this값이 undefined가 됨(비 Strict모드에서는 함수 안의 this의 값은 전역 객체의 참조)

3. with문은 사용 불가

4. 함수 정의문에 같은 이름의 인수가 있으면 문법 오류가 발생

5. 객체에 같은 이름의 프로퍼티가 있으면 문법 오류가 발생함

6. NaN, Infinity, undefined를 표기하면 TypeError가 발생함

7. argument[i]는 호출되었을 때 그 값을 유지함.(비 Strict모드에서는 argument[i]가 인자의 별명으로 한쪽을 수정하면 다른 한쪽도 수정됨)

8. argument.callee를 읽을 수 없음. 읽기를 시도하면 TypeError가 발생

9. eval로 실행한 코드는 호출자의 유효 범위 안에 새로운 변수나 함수를 선언할 수 없음.(eval사용은 지양해야 함)


---

**<u>Strict모드 설정</u>**


**프로그램을 Strict모드로 설정하려면 함수의 첫머리 또는 스크립트의 첫머리(모든 문장 앞에) "use strict"을 입력함**

1. 함수에 Strict모드 적용

```javascript
function f(x){
    "use strict";
    y = x;
}
f(2);
```

-함수에 Strict모드를 적용한 경우, 그 함수에 중첩된 함수에도 Strict모드가 적용됨


-Strict를 실행하기 전에는 y에 변수 선언하지 않아도 전역변수로써 처리하여 정상적으로 프로그램이 실행됨 

-> but, strict모드에서는 이를 오류로 취급함 


2. Script에 Strict모드 적용

```html
<script>
    "use strict"; //-> 이 스크립트는 strict모드로 동작함
</script>
<script>
    x = 2; //-> 이 스크립트는 strict모드로 동작하지 않음
</script>
```

-Strict모드는 '스크립트 단위'로 적용됨


---

* #### 스타일 가이드 활용

**스타일 가이드**: 프로그램을 작성할 때 버그를 피하고 가독성을 높이기 위해 권장되는 코딩 규칙을 일컫음


<u>스타일 가이드 활용 시 참고</u>

-여러 사람이 함께 프로그램을 개발할 때 스타일 가이드를 참고하여 전체적인 코딩 규칙을 정해 두기를 권장(여러사람이 개발하다보면 자기만의 방식대로 코딩 방법이 적용되기 때문에 중구낭방 식으로 작성될 위험이 있음)


_자바스크립트의 대표적인 스타일 가이드_

1. Google JavaScript Style Guide

    - 구글이 제공하는 스타일 가이드
    
    - 프로그램의 스타일을 확인하는 도구도 함께 제공

    - Closure Linter이라고 하는 프로그램이며 리눅스, 맥, 윈도용이 마련


2. Javascript style guide - MDN Docs

    - 모질라가 제공하는 스타일 가이드

    - 파이어폭스용으로 작성되어 있어 ECMAScript의 범위를 넘어서는 내용이 몇 군데 포함되어 있음


3. jQuery JavaScript Style Guide 

    - jQuery가 제공하는 스타일 가이드


4. Airbnb Javascript style Guide

    - 숙박 공유 서비스 기업인 Airbnb가 제공하는 스타일 가이드

    - GitHub에서 가장 인기있는 문서


---

* #### console 디버깅


**디버깅(debugging) 또는 디버그(debug)**

컴퓨터 프로그램 개발 단계 중에 발생하는 시스템의 논리적인 오류나 비정상적 연산(버그)를 찾아내고 그 원인을 밝히고 수정하는 작업


_예시_

실행 중인 함수의 호출 스택

```javascript
function f(){
    function g(){
        function h(){
            console.trace();
        }
        h();
    }
    g();
}
f();
```

console.trace()를 이용하면 실행 중인 함수가 어디에서 호출되었는지를 알 수 있음


---

* #### 디버거 기능


-웹 브라우저의 개발자 도구를 사용한 디버깅

-현재의 변수 값과 처리가 어떻게 진행되고 있는지를 console.log를 사용할 때 보다 더 자세하게 알 수 있음

-실행 중인 코드를 수정하는 기능을 가지고 있어 때로는 따로 코드 수정을 하지 않고 디버깅할 수도 있음


_주요 자바스크립트 실행 환경이 제공하는 디버거_



---

* #### 프로그램 테스트

**프로그램 테스트**

-프로그램이 의도한 대로 동작하는지 확인하는 작업


-프로그램으로 버그를 찾을 수는 있지만, <u>버그가 없다는 사실을 증명할 수는 없음</u>


-특히 대규모 프로그램에서 버그를 완전히 제거하기란 매우 어렵기 때문에 규정된 프로그램 테스트를 통과하면 어느 정도의 품질을 확보한 것으로 간주


1. 단위 테스트


    - 각 함수의 동작을 확인하는 테스트

    - 주로 설계대로 함수가 작동하는지 테스트하여 적절한 알고리즘이 사용되었는지를 확인


2. 통합 테스트


    - 단위 테스트를 통과한 프로그램을 결합해서 수행하는 테스트

    - 상태 다이어그램 등을 바탕으로 동작을 확인하거나 결합한 프로그램이 원하는 기능을 구현했는지 검증하는 기능 테스트


3. 시스템 테스트


    - 모든 프로그램을 결합하여 전체 프로그램이 사양에 따라 작동하는지 확인하는 테스트

    - 단순한 동작확인은 물론 보안성 및 사용성 측면도 평가

    - 프로그램이 부하(사용자 수나 장시간의 연속 작업 등)를 얼마만큼 견딜 수 있는지를 확인


4. 운용 테스트


    - 완성된 프로그램을 실제 사용자가 테스트

    - 주로 프로그램 결함이나 사용자가 사용하는 데 따르는 어려움 등을 확인함


---

### 예외처리


* #### 예외 exception

오류 및 예외 조건이 발생한 사실을 알려주는 신호


**예외를 던진다(throw)**: 예외를 던져 오류 또는 예외 조건이 발생했다는 사실을 통지

**예외를 받는다(catch)**: 예외를 받는 작업으로, 예외를 받아서 처리하는 부분을 가르켜 <u>예외처리기</u>라고 함


* #### throw문

예외를 던짐 


**throw 표현식;**


-표현식으로는 어떤 타입의 값도 지정할 수 있음(사용자에게 표시할 오류 메시지가 포함된 문자열이나 오류 코드를 의미하는 숫자도 허용)


-그러나, **일반적으로는** Error객체나 Error객체를 상속받은 객체를 지정


_예시_

인수로 받기로 약속한 _배열_이 전달되지 않았을 때 예외를 던지는 경우

```javascript
function permutation(a){
    if(!(a instanceof Array)){
        throw new Error(a + "is not an array");
    }
}
permutation("ABC"); // -> Error: ABC is not an array
```

```javascript
function permutation(a){
    if(!(Array.isArray(a))){ //Array.isArray(a):배열이면 true를 아니면 false
        throw new Error(a + "is not an array");
    }
}
permutation("ABC");
```


**타입의 판정**

1. typeof

함수인지를 판정할 때 typeof 연산자 이용

```javascript
if (typeof callback != "function") throw new Error(callback + "is not a function");
```


2. instanceof 

함수 타입 외의 객체 타입이면 instanceof연산자를 이용

**why?** typeof연산자를 이용하면 함수 타입 외의 객체 타입의 경우에는 모두 "object를 반환하여 어떤 타입의 객체인지 확인할 수 없음

```javascript
if(!(map instanceof Map)) throw  new Error(map + "is not a Map object");
```


---

* #### Error객체

Error객체는 범용적인 예외를 표현하기 위한 객체고, 나머지는 특정 예외가 발생했을 때 표현하기 위한 객체


_예외를 표현하는 내장 객체의 생성자_

|생성자|생성하는 인스턴스|
|-------|--------------|
|Error|범용적인 예외 객체|
|EvalError|eval함수와 관련해서 발생한 예외 객체|
|RangeError|숫자 값이 허용 범위를 벗어났을 때 발생하는 예외 객체|
|ReferenceError|잘못된 참조를 만났을 때 발생하는 예외 객체|
|SyntaxError|자바스크립트 문법에 어긋나는 구문을 만났을 때 발생하는 예외 객체|
|TypeError|변수 및 인수 타입이 유효하지 않을 때 발생하는 예외 객체|
|URIError|encodURI와 decodeURI메서드에 잘못된 인수가 전달되었을 때 발생하는 예외 객체|


위의 생성자를 통해 생성한 내장 객체는 모두 Error.prototype의 프로퍼티와 메서드를 상속받음 

_프로퍼티_

1. message: 오류 메시지를 뜻하는 문자열

2. name: 오류 이름을 뜻하는 문자열


_메서드

1. toString: 지정된 객체를 표현하는 문자열을 반환

![image](https://user-images.githubusercontent.com/83913407/130793864-04145d49-e118-49ba-b189-0e1caa08a33d.png)


---

* #### try/catch/finally 문

예외가 던져졌을 때 그것을 잡아서 처리

```javascript
try{
    //이곳에 실행할 코드를 적음(예외가 발생할 수 있는 코드)
}catch(exception){
    //이 블록은 try 블록에서 예외가 발생했을 때 실행됨
    //exception에는 던져진 예외 값이 들어옴. 이 값을 바탕으로 예외 처리
}finally{
    //이 블록 안의 코드는
    //try 블록 코드와 catch블록 코드가 실행된 이후에 반드시 실행됨
}
```

1. try블록 

-try블록 안에는 예외가 발생할 가능성이 있는 코드를 작성. 

-try블록 다음에 catch블록과 finally블록 중 하나를 작성하거나 모두를 작성함(단, catch가 작성되지않을면 예외가 발생했을 때 프로그램이 종료됨)


2. catch블록 

-catch블록 안에는 try블록에서 예외가 발생했을 때 실행할 문장을 작성

-catch블록 뒤의 괄호에는 변수를 입력할 수 있음. 그 변수에는 try블록에서 던지 예외 값(Error객체 등)이 들어옴(catch블록 처리가 끝나면 그 변수는 사용할 수 없게 됨)

-catch블록은 마치 하나의 함수처럼 동작함, catch블록은 예외 이벤트 처리기에 비유할 수 있음


3. finally블록

-예외 처리의 마지막에 반드시 실행도미

-try블록의 내부 또는 catch블록 내부에 return문, continue문, break문이 실행되어 try/catch/finally문장을 빠져나오는 경우에는 빠져나오기 직전에 finally블록 안의 코드가 실행됨


---

**<u>예외가 여러개 발생했을 때</u>**

```javascript
try{
    //이 지점에서 오류가 발생한다고 가정
}catch(e){
    if(e instanceof TypeError){
        // TypeError가 발생했을 때의 처리를 작성
    }else if(e instanceof ReferenceError){
        // ReferenceError가 발생했을 때의 처리를 작성
    }else{
        //그 외의 예외가 발생했을 때의 처리를 작성
    }
}
```

catch블록 안에 예외 유형별로 처리를 작성하면 다양한 유형의 예외를 처리할 수 있음 


---

**<u>예외의 전파</u>**

예외는 스택을 **거슬러 올라가며** 전파

```javascript
try{
    f();
}catch(e){
    console.log("예외를 캐치함 ->" + e);
}
function f() {g();}
function g() {h();}
function h() { throw new Error("오류가 발생했습니다");}
```


---

**<u>비동기 처리의 콜백 함수가 던진 예외 처리</u>**

비동기 처리의 콜백함수가 던진 예외는 콜백함수를 넘긴 함수로 전파가 되지 않음 => 예외가 캐치되지 않음

```javascript
try{
    setTimeout(function throwError(){
        throw new Error("오류가 발생했습니다");
    },1000);
}catch(e){
    console.log("예외를 처리함 ->" + e);
}
// -> Uncaught Error: 오류가 발생했습니다
```

**ECMAScript 6부터 추가된 제너레이터를 활용하면 비동기 처리의 콜백 함수가 던지 예외도 catch할 수 있음**

```javascript
function sleepAndError(g,n){
    for(var i=0;i<n;i++) console.log(i);
    g.throw(new Error("오류가 발생했습니다"));
}
function run(callback, ...argsList){
    var g = (function* (cb, args){
        try{
            yield cb(g, ...args);
        }catch(e){
            console.log("예외 캐치 =>" + e);
        }
    })(callback, argsList);
    g.next();
}
run(sleepAndError, 10);
```


---

**<u>반목문에서 빠져나오기</u>**

```javascript
var a = [0,1,2,3,4,5,6,7,8,9];
try {
    a.forEach(function(v,i,a){
        if(i>5){
            throw false;
        }
        return a[i] = v*v;
    });
}catch(e){
    if(e) throw e;
}
console.log(e); // -> [0,1,4,9,16,25,6,7,8,9]
```

인덱스가 6부터는 if문이 true여서 throw의 값이 false가 던져짐

-> catch는 예외 값이 true일때 실행하므로, 위의 경우에는 catch가 아닌 console.log(e)가 실행됨